all:
  children:
    prod:
      vars:
        env: production
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        worker01:
          ansible_host: 172.31.93.227
          hostname: AnsibleWorker01

        worker02:
          ansible_host: 172.31.85.58
          hostname: AnsibleWorker02

        worker03:
          ansible_host: 172.31.90.221
          hostname: AnsibleWorker03
