all:
  children:
    prod:
      vars:
        env: production
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        worker03:
          ansible_host: 172.31.90.221
          hostname: AnsibleWorker03
  
