- name: deploy wordpress using a role
  hosts: worker03
  become: true
  vars:
    edit_hostname: "no"
    hostname: "AnsibleWorker03"
  roles:
    - hexotic.docker_role
    - hexotic.wordpress_role

